# HOLY LABEL CSS外部化戦略プラン
# 目標: 102,439バイトのCSS → 大幅削減によるBASE制限内達成

name: "HOLY LABEL CSS Externalization Project"
version: "2.0.0"
description: "BASE テーマ最適化プロジェクト - CSS外部ライブラリシステム"

# Phase 1: 基盤CSS (実装済み)
phase_1:
  foundation:
    target_file: "foundation.css"
    description: "CSS変数・リセット・フォント設定"
    estimated_size: "~5.8KB"
    
  layout:
    target_file: "layout.css"  
    description: "ハンバーガーメニュー・ロゴ・ナビゲーション"
    estimated_size: "~8.2KB"

# Phase 2: コンポーネントCSS (実装済み)
phase_2:
  base_menu:
    target_file: "base-menu.css"
    description: "BASEメニュー・ナビゲーション・検索"
    estimated_size: "~6.5KB"
    
  product_components:
    target_file: "product-components.css"
    description: "商品グリッド・商品コンポーネント"
    estimated_size: "~7.2KB"
    
  animations:
    target_file: "animations.css"
    description: "アニメーション・ヒーローイメージ"
    estimated_size: "~3.8KB"

# Phase 3: 商品詳細・フォーム・レスポンシブ (新規)
phase_3:
  product_detail:
    target_file: "product-detail.css"
    description: "商品詳細ページ・購入フォーム・画像ギャラリー"
    estimated_size: "~12KB"
    css_sections:
      - "商品詳細レイアウト"
      - "商品購入フォーム"
      - "画像ギャラリー・サムネイル"
      - "一覧に戻るボタン"
      
  forms:
    target_file: "forms.css"
    description: "フォーム要素・入力・ボタン・検索"
    estimated_size: "~8KB"
    css_sections:
      - "入力フィールド共通"
      - "検索フォーム"
      - "ニュースレターフォーム"
      - "エラー・成功メッセージ"
      
  responsive:
    target_file: "responsive.css"
    description: "レスポンシブ・メディアクエリ"
    estimated_size: "~9KB"
    css_sections:
      - "モバイル対応"
      - "タブレット対応"
      - "デスクトップ対応"
      
  footer_pages:
    target_file: "footer-pages.css"
    description: "フッター・ページコンテンツ・BASE要素"
    estimated_size: "~5KB"
    css_sections:
      - "フッター"
      - "ページコンテンツ"
      - "BASE固有要素"

# Phase 4: 特殊ページ・UI・統合機能 (新規)
phase_4:
  special_pages:
    target_file: "special-pages.css"
    description: "LOOKBOOK・About・Contact・特定商取引法ページ専用スタイル"
    estimated_size: "~8KB"
    css_sections:
      - "LOOKBOOKページ（ブログ）スタイル"
      - "Aboutページスタイル"
      - "Contactページスタイル" 
      - "特定商取引法・プライバシーポリシーページ"
      - "ページ別モバイル対応"
      
  ui_components:
    target_file: "ui-components.css"
    description: "モーダル・PayID・関連商品・Ajax読み込み・アニメーション"
    estimated_size: "~7KB"
    css_sections:
      - "モーダル表示機能"
      - "PayIDウィジェット"
      - "関連商品表示"
      - "Ajax読み込みボタン"
      - "キーフレームアニメーション"
      
  base_integration:
    target_file: "base-integration.css"
    description: "BASE多言語・Instagram連携・外貨表示・アプリ統合"
    estimated_size: "~8KB"
    css_sections:
      - "BASE多言語切り替えUI（I18n）"
      - "Instagram固定ボタン"
      - "外貨表示対応"
      - "BASEアプリ統合機能"
      - "情報バナー対応"

# Phase 5: 残存スタイル外部化 (NEW)
phase_5:
  remaining_styles:
    target_file: "remaining-styles.css"
    description: "HTMLから分離した残存インラインCSS"
    estimated_size: "~15KB"
    css_sections:
      - "z-index変数定義"
      - "ナビゲーションエリア"
      - "商品ステータス表示"
      - "商品グリッド・商品情報"
      - "ソーシャル・商品注意書き"
      - "ページコンテンツ"
      - "ハンバーガーボタン"
      - "ローディング・状態管理"
      - "BASE固有スタイル調整"

# バンドル設定
bundles:
  foundation_bundle:
    files: ["foundation.min.css", "layout.min.css"]
    output: "foundation-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/foundation-bundle.min.css"
    
  components_bundle:
    files: ["base-menu.min.css", "product-components.min.css", "animations.min.css"]
    output: "components-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/components-bundle.min.css"
    
  # Phase 3 新規バンドル
  product_detail_bundle:
    files: ["product-detail.min.css"]
    output: "product-detail-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/product-detail-bundle.min.css"
    
  forms_bundle:
    files: ["forms.min.css"]
    output: "forms-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/forms-bundle.min.css"
    
  responsive_bundle:
    files: ["responsive.min.css"]
    output: "responsive-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/responsive-bundle.min.css"
    
  footer_pages_bundle:
    files: ["footer-pages.min.css"]
    output: "footer-pages-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/footer-pages-bundle.min.css"
    
  # Phase 4 新規バンドル
  special_pages_bundle:
    files: ["special-pages.min.css"]
    output: "special-pages-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/special-pages-bundle.min.css"
    
  ui_components_bundle:
    files: ["ui-components.min.css"]
    output: "ui-components-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/ui-components-bundle.min.css"
    
  base_integration_bundle:
    files: ["base-integration.min.css"]
    output: "base-integration-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/base-integration-bundle.min.css"

  # Phase 5 新規バンドル
  remaining_styles_bundle:
    files: ["remaining-styles.min.css"]
    output: "remaining-styles-bundle.min.css"
    cdn_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/remaining-styles-bundle.min.css"

# CDN設定
cdn:
  provider: "jsDelivr"
  base_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/"
  cache_time: "24h"
  version: "1.2.0"

# 削減目標
targets:
  phase_3_reduction: "34000 bytes"
  cumulative_target: "67000 bytes"
  final_goal: "15000 bytes or less"

project:
  name: "HOLY LABEL CSS Externalization"
  target_reduction: "95%以上（約97,000バイト削減）"
  final_target: "HTMLファイル15,000バイト以内"

current_analysis:
  total_html_size: 139602  # bytes
  css_section_size: 102439  # bytes (73.3%)
  css_lines: "37-2999"
  js_externalized: 20399  # bytes already reduced

css_externalization_phases:
  
  phase1_foundation:
    name: "基盤CSS外部化"
    target_components:
      - "CSS変数・リセットスタイル"
      - "フォント設定・基本レイアウト"
      - "カラーテーマ・タイポグラフィ"
    estimated_size: "8000-12000 bytes"
    priority: "highest"
    
  phase2_layout:
    name: "レイアウトCSS外部化"
    target_components:
      - "ヘッダー・ナビゲーション"
      - "ハンバーガーメニュー・ロゴ配置"
      - "BASEメニュー・レスポンシブ"
    estimated_size: "15000-20000 bytes"
    priority: "high"
    
  phase3_components:
    name: "コンポーネントCSS外部化"
    target_components:
      - "商品グリッド・カード"
      - "商品画像・価格表示"
      - "モーダル・フォーム"
    estimated_size: "25000-30000 bytes"
    priority: "high"
    
  phase4_advanced:
    name: "高度機能CSS外部化"
    target_components:
      - "アニメーション・トランジション"
      - "スクロール効果・インタラクション"
      - "カルーセル・ギャラリー"
    estimated_size: "20000-25000 bytes"
    priority: "medium"
    
  phase5_responsive:
    name: "レスポンシブCSS外部化"
    target_components:
      - "モバイル専用スタイル"
      - "メディアクエリ・ブレークポイント"
      - "デバイス別最適化"
    estimated_size: "15000-20000 bytes"
    priority: "medium"

build_system:
  tools:
    - "Node.js + PostCSS"
    - "cssnano (minification)"
    - "autoprefixer"
  output_format:
    individual_files: "個別CSSライブラリ"
    bundled_files: "統合CSSバンドル"
    naming_convention: "holy-label-[component].min.css"

cdn_distribution:
  platform: "jsDelivr"
  base_url: "https://cdn.jsdelivr.net/gh/irutomo/holy-label-js-divede@main/css/dist/"
  versioning: "GitHub releases"
  cache_strategy: "automatic CDN cache"

base_template_integration:
  approach: "段階的外部リンク追加"
  fallback_strategy: "CDN利用のみ（BASEテーマ仕様準拠）"
  loading_optimization: "preload hints"
  critical_css: "最小限インライン維持"

compatibility:
  base_requirements:
    - "単一HTMLファイル制約対応"
    - "外部ファイル参照不可"
    - "CDNのみ利用可能"
  browser_support:
    - "Modern browsers (ES6+)"
    - "Mobile responsive"
    - "Progressive enhancement"

performance_targets:
  css_size_reduction: "95%+"
  loading_performance: "LCP改善"
  rendering_optimization: "CLS最小化"
  
implementation_phases:
  week1: "Foundation CSS外部化"
  week2: "Layout CSS外部化"
  week3: "Components CSS外部化"
  week4: "Advanced + Responsive CSS外部化"
  week5: "最適化・統合テスト"

success_metrics:
  primary: "HTMLファイル15,000バイト以内達成"
  secondary: "CSS読み込み速度向上"
  tertiary: "保守性・拡張性向上" 